version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: alembic
    versions:
    - 1.5.2
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: sentry-sdk
    versions:
    - 0.19.5
    - 0.20.1
    - 0.20.3
  - dependency-name: pytest
    versions:
    - 6.2.1
    - 6.2.2
  - dependency-name: marko
    versions:
    - 1.0.1
  - dependency-name: packaging
    versions:
    - "20.8"
  - dependency-name: zipp
    versions:
    - 3.4.0
